# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('key', models.CharField(blank=True, max_length=1024, null=True)),
                ('url', models.URLField(blank=True, max_length=4096, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cryptos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('symbol', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('key', models.CharField(blank=True, max_length=1024, null=True)),
                ('buy', models.FloatField(blank=True, null=True)),
                ('sell', models.FloatField(blank=True, null=True)),
                ('last', models.FloatField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=1024, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('international_price_dollar', models.FloatField(blank=True, null=True)),
                ('international_price_inr', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
