# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20180111_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=4096)),
                ('last_name', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=1024, null=True)),
                ('message', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
