# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptos',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=1024, null=True),
        ),
    ]
