# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20180120_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptos',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, max_length=1024, null=True),
        ),
    ]
