# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
