# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20180118_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
