# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_faq'),
        ('crypto', '0004_auto_20180120_2000'),
    ]

    operations = [
    ]
