# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_merge_20180126_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptos',
            name='available_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='data_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='market_cap_inr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='market_cap_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='max_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='percent_change_1h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='price_btc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='price_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='total_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='volume_inr_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptos',
            name='volume_usd_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptos',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
