# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_auto_20180126_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianCryptos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('coin_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('symbol', models.CharField(blank=True, max_length=1024, null=True)),
                ('international_price_inr', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('price_usd', models.FloatField(blank=True, null=True)),
                ('price_btc', models.FloatField(blank=True, null=True)),
                ('volume_usd_24h', models.FloatField(blank=True, null=True)),
                ('market_cap_usd', models.FloatField(blank=True, null=True)),
                ('available_supply', models.FloatField(blank=True, null=True)),
                ('total_supply', models.FloatField(blank=True, null=True)),
                ('max_supply', models.FloatField(blank=True, null=True)),
                ('percent_change_1h', models.FloatField(blank=True, null=True)),
                ('percent_change_24h', models.FloatField(blank=True, null=True)),
                ('percent_change_7d', models.FloatField(blank=True, null=True)),
                ('data_last_updated', models.CharField(blank=True, max_length=1024, null=True)),
                ('volume_inr_24h', models.FloatField(blank=True, null=True)),
                ('market_cap_inr', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='api',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='first_name',
            field=models.TextField(max_length=2000),
        ),
    ]
