# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_exchanges_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='key',
            new_name='exhchange_id',
        ),
        migrations.RenameField(
            model_name='exchanges',
            old_name='key',
            new_name='exhchange_id',
        ),
        migrations.RemoveField(
            model_name='exchanges',
            name='url',
        ),
    ]
