# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_auto_20180130_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API',
            new_name='ExchangesInfo',
        ),
    ]
