# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0013_exchangesinfo_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangesinfo',
            name='website',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
