# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0014_auto_20180130_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchanges',
            old_name='exhchange_id',
            new_name='exchange_id',
        ),
        migrations.RenameField(
            model_name='exchangesinfo',
            old_name='exhchange_id',
            new_name='exchange_id',
        ),
    ]
