# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0016_exchangesinfo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangesinfo',
            name='bitcoin_org_recognized',
            field=models.NullBooleanField(default=False),
        ),
    ]
