# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0017_exchangesinfo_bitcoin_org_recognized'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('provider', models.CharField(blank=True, max_length=1024, null=True)),
                ('token', models.CharField(blank=True, max_length=10000, null=True)),
                ('uid', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
