# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0019_auto_20180210_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_currency_code',
            field=models.CharField(default='INR', max_length=1024),
        ),
    ]
